version: "3.5"

services:

  trailers_api:
    image: trailers-api
    container_name: trailers-api
    restart: on-failure
    hostname: trailers_api
    networks:
      trailers-network:
        ipv4_address: 172.25.0.10
    ports:
      - 3000:3000
    environment:
      REDIS_TTL: 18000
      REDIS_URL: redis://172.25.0.2:6379
      TMDB_API_KEY: ${TMDB_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis
    container_name: trailers-redis
    networks:
      trailers-network:
        ipv4_address: 172.25.0.2
    ports:
      - 6379:6379

networks:
  trailers-network:
    name: trailers-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
